# SPC Genome Project Configuration
# Edit paths below to match your system setup

# Data paths
data:
  # Main data directory (relative to project root)
  base_dir: "./data"

  # Raw input sequencing files (symlinked)
  read1: "./data/K562_tree/raw/k562_tree_1_S1_R1_001.fastq.gz"
  read2: "./data/K562_tree/raw/k562_tree_1_S1_R2_001.fastq.gz"

  # Read count (from sequencing run)
  # Estimate: ~9 billion reads (adjust based on actual sequencing report)
  read_count: 9000000000

# Reference genome
reference:
  # Directory containing genome fasta, fasta index, and BWA index (GATK bundle for hg38)
  # Fasta: /shared/biodata/reference/GATK/hg38/Homo_sapiens_assembly38.fasta
  # BWA index: /shared/biodata/reference/GATK/hg38/BWAIndex/Homo_sapiens_assembly38.fasta.64.*
  # This reference works for both alignment and GATK variant calling
  genome_dir: "/shared/biodata/reference/GATK/hg38"

# Processing parameters
processing:
  # Number of chunks for parallel processing
  n_chunks: 500

  # Temporary directory for FASTQ chunks and intermediate files
  # Default: /hpc/temp/srivatsan_s/SPC_genome_preprocessing
  tmp_dir: "/hpc/temp/srivatsan_s/SPC_genome_preprocessing"

# Output settings
output:
  # Base output directory
  base_dir: "./results"

  # Sample name prefix
  sample_name: "K562_tree"

# Cluster settings (SLURM)
cluster:
  # Default CPUs per task
  cpus: 2

  # Default memory (GB)
  memory: 16

  # Default time limit (format: D-HH:MM:SS)
  time: "2-0"

  # Partition
  partition: "campus"
