"""
CeNGEN cell-type -> tissue / founder-lineage annotation for C. elegans (hermaphrodite).

Founder key (Sulston et al. 1983):

                       P0  (zygote)
                      /   \
                    AB     P1
                           / \
                         EMS  P2
                         / \   / \
                        MS  E C   P3
                                  / \
                                  D   P4
                                      |
                                      Z2/Z3 (germline)

`FOUNDER` gives the DOMINANT founder blastomere for each CeNGEN label.
`LINEAGE_MIXED` is True where the cluster contains cells of more than one founder
origin -- for those, `FOUNDER_COMPOSITION` spells out the split and the dominant
label alone is NOT a valid lineage ground truth.

Labels not present in the tables (e.g. custom or dataset-specific annotations) are
passed through by `annotate()` as tissue "Unknown" / founder "NA" rather than raising;
use `check_labels()` to see what is unmapped, or `on_missing="raise"` for the strict
behaviour.

Provenance: founder assignments were computed by resolving each constituent cell's
Sulston lineage name in the WormAtlas "Complete C. elegans Cell List"
(https://www.wormatlas.org/celllistsulston.htm, adapted from Sulston & White 1988),
walking postembryonic blast-cell prefixes (P1-P12, V1-V6, H0-H2, T, QL/QR, M,
Z1/Z4, K, W, Y, G1/G2) back to their embryonic lineage names.
See CENGEN_LINEAGE_ANNOTATION.md for the full write-up and caveats.
"""

TISSUE_COARSE = {
    'Epidermis': 'Epithelium',
    'ASG': 'Neuron',
    'Pharyngeal_muscle': 'Muscle',
    'PHB': 'Neuron',
    'PVT': 'Neuron',
    'VB02': 'Neuron',
    'Body_wall_muscle': 'Muscle',
    'ASK': 'Neuron',
    'ADL': 'Neuron',
    'IL2_LR': 'Neuron',
    'PHA': 'Neuron',
    'AVD': 'Neuron',
    'AVE': 'Neuron',
    'AWA': 'Neuron',
    'I4': 'Neuron',
    'ADE': 'Neuron',
    'PVW': 'Neuron',
    'SMB': 'Neuron',
    'ASH': 'Neuron',
    'SDQ': 'Neuron',
    'AVL': 'Neuron',
    'NSM': 'Neuron',
    'RMF': 'Neuron',
    'RMD_DV': 'Neuron',
    'Unannotated': 'Unknown',
    'CEP': 'Neuron',
    'SIA': 'Neuron',
    'ALA': 'Neuron',
    'Coelomocyte': 'Other_mesoderm',
    'AIZ': 'Neuron',
    'RMH': 'Neuron',
    'PLN': 'Neuron',
    'PVP': 'Neuron',
    'RIA': 'Neuron',
    'Germline': 'Germline',
    'SMD_stressed': 'Neuron',
    'SIB': 'Neuron',
    'M5': 'Neuron',
    'RIR': 'Neuron',
    'URX': 'Neuron',
    'Uterine_cell': 'Somatic_gonad',
    'RIV': 'Neuron',
    'Seam_cell': 'Epithelium',
    'AIN': 'Neuron',
    'PQR': 'Neuron',
    'AVH': 'Neuron',
    'AVK': 'Neuron',
    'VB01': 'Neuron',
    'RID': 'Neuron',
    'I3': 'Neuron',
    'Gonadal_sheath_cell': 'Somatic_gonad',
    'Glia_1': 'Glia',
    'ASJ': 'Neuron',
    'AWC_ON': 'Neuron',
    'AVG': 'Neuron',
    'AVA': 'Neuron',
    'ASER': 'Neuron',
    'DA': 'Neuron',
    'URB': 'Neuron',
    'AVB': 'Neuron',
    'AVM': 'Neuron',
    'PVQ': 'Neuron',
    'CEPsh': 'Glia',
    'M2': 'Neuron',
    'M1': 'Neuron',
    'Arcade_cell': 'Epithelium',
    'RIF': 'Neuron',
    'MI': 'Neuron',
    'Spermatheca': 'Somatic_gonad',
    'PVR': 'Neuron',
    'AIY': 'Neuron',
    'ADF': 'Neuron',
    'PVC': 'Neuron',
    'RIH': 'Neuron',
    'MC': 'Neuron',
    'Unknown_non_neuronal': 'Unknown',
    'HSN': 'Neuron',
    'I2': 'Neuron',
    'Sperm': 'Germline',
    'VD_DD': 'Neuron',
    'RIC': 'Neuron',
    'AQR': 'Neuron',
    'VC': 'Neuron',
    'Glia_3': 'Glia',
    'RIV_stressed': 'Neuron',
    'DB01': 'Neuron',
    'VA': 'Neuron',
    'Intestine': 'Intestine',
    'VB': 'Neuron',
    'SAB': 'Neuron',
    'OLL': 'Neuron',
    'URY': 'Neuron',
    'BAG': 'Neuron',
    'ALM': 'Neuron',
    'IL2_DV': 'Neuron',
    'AIA': 'Neuron',
    'Excretory_gland_cell': 'Gland',
    'M4': 'Neuron',
    'RME_DV': 'Neuron',
    'DB': 'Neuron',
    'URA': 'Neuron',
    'Vulval_muscle': 'Muscle',
    'Distal_tip_cell': 'Somatic_gonad',
    'Anal_muscle': 'Muscle',
    'PHC': 'Neuron',
    'RME_LR': 'Neuron',
    'PHsh': 'Glia',
    'I5': 'Neuron',
    'RIB': 'Neuron',
    'RIM': 'Neuron',
    'ASI': 'Neuron',
    'AIM': 'Neuron',
    'BDU': 'Neuron',
    'DVB': 'Neuron',
    'AIB': 'Neuron',
    'I1': 'Neuron',
    'Spermathecal-uterine_junction_or_uterine_toroid': 'Somatic_gonad',
    'RIS': 'Neuron',
    'RIP': 'Neuron',
    'DVC': 'Neuron',
    'RMD_LR': 'Neuron',
    'I6': 'Neuron',
    'AVJ': 'Neuron',
    'AMso': 'Glia',
    'AUA': 'Neuron',
    'Unknown_non-neuronal_3': 'Unknown',
    'RMG': 'Neuron',
    'PLM': 'Neuron',
    'Body_wall_muscle_anterior': 'Muscle',
    'Marginal_cell': 'Epithelium',
    'hmc': 'Other_mesoderm',
    'Pharyngeal_gland_cell': 'Gland',
    'PDE': 'Neuron',
    'AWC_OFF': 'Neuron',
    'AVF': 'Neuron',
    'AWB': 'Neuron',
    'AFD': 'Neuron',
    'Excretory_cell': 'Gland',
    'Vulval_cells': 'Epithelium',
    'Glia_5': 'Glia',
    'FLP': 'Neuron',
    'SMD': 'Neuron',
    'CAN': 'Neuron',
    'ADA': 'Neuron',
    'Rectal_gland': 'Gland',
    'Glia_4': 'Glia',
    'Unknown_non_neuronal_2': 'Unknown',
    'LUA': 'Neuron',
    'ASEL': 'Neuron',
    'AMsh': 'Glia',
    'RIG': 'Neuron',
    'PHso': 'Glia',
    'Glia_2': 'Glia',
    'OLQ': 'Neuron',
    'IL1': 'Neuron',
    'M3': 'Neuron',
    'ALN': 'Neuron',
    'AS': 'Neuron',
    'DA9': 'Neuron',
    'DVA': 'Neuron',
    'PDA': 'Neuron',
    'PDB': 'Neuron',
    'PVD': 'Neuron',
    'PVM': 'Neuron',
    'PVN': 'Neuron',
    'SAA': 'Neuron',
    'VA12': 'Neuron',
    'VC_4_5': 'Neuron',
    'XXX': 'Epithelium',
}

TISSUE_MEDIUM = {
    'Epidermis': 'Hypodermis',
    'ASG': 'Sensory_neuron',
    'Pharyngeal_muscle': 'Pharyngeal_muscle',
    'PHB': 'Sensory_neuron',
    'PVT': 'Interneuron',
    'VB02': 'Motor_neuron',
    'Body_wall_muscle': 'Body_wall_muscle',
    'ASK': 'Sensory_neuron',
    'ADL': 'Sensory_neuron',
    'IL2_LR': 'Sensory_neuron',
    'PHA': 'Sensory_neuron',
    'AVD': 'Interneuron',
    'AVE': 'Interneuron',
    'AWA': 'Sensory_neuron',
    'I4': 'Pharyngeal_neuron',
    'ADE': 'Sensory_neuron',
    'PVW': 'Interneuron',
    'SMB': 'Motor_neuron',
    'ASH': 'Sensory_neuron',
    'SDQ': 'Interneuron',
    'AVL': 'Motor_neuron',
    'NSM': 'Pharyngeal_neuron',
    'RMF': 'Motor_neuron',
    'RMD_DV': 'Motor_neuron',
    'Unannotated': 'Unknown',
    'CEP': 'Sensory_neuron',
    'SIA': 'Interneuron',
    'ALA': 'Interneuron',
    'Coelomocyte': 'Coelomocyte',
    'AIZ': 'Interneuron',
    'RMH': 'Motor_neuron',
    'PLN': 'Interneuron',
    'PVP': 'Interneuron',
    'RIA': 'Interneuron',
    'Germline': 'Germline',
    'SMD_stressed': 'Motor_neuron',
    'SIB': 'Interneuron',
    'M5': 'Pharyngeal_neuron',
    'RIR': 'Interneuron',
    'URX': 'Sensory_neuron',
    'Uterine_cell': 'Somatic_gonad',
    'RIV': 'Motor_neuron',
    'Seam_cell': 'Seam',
    'AIN': 'Interneuron',
    'PQR': 'Sensory_neuron',
    'AVH': 'Interneuron',
    'AVK': 'Interneuron',
    'VB01': 'Motor_neuron',
    'RID': 'Interneuron',
    'I3': 'Pharyngeal_neuron',
    'Gonadal_sheath_cell': 'Somatic_gonad',
    'Glia_1': 'Glia_unassigned',
    'ASJ': 'Sensory_neuron',
    'AWC_ON': 'Sensory_neuron',
    'AVG': 'Interneuron',
    'AVA': 'Interneuron',
    'ASER': 'Sensory_neuron',
    'DA': 'Motor_neuron',
    'URB': 'Sensory_neuron',
    'AVB': 'Interneuron',
    'AVM': 'Sensory_neuron',
    'PVQ': 'Interneuron',
    'CEPsh': 'Glia_sheath',
    'M2': 'Pharyngeal_neuron',
    'M1': 'Pharyngeal_neuron',
    'Arcade_cell': 'Arcade_marginal',
    'RIF': 'Interneuron',
    'MI': 'Pharyngeal_neuron',
    'Spermatheca': 'Somatic_gonad',
    'PVR': 'Interneuron',
    'AIY': 'Interneuron',
    'ADF': 'Sensory_neuron',
    'PVC': 'Interneuron',
    'RIH': 'Interneuron',
    'MC': 'Pharyngeal_neuron',
    'Unknown_non_neuronal': 'Unknown',
    'HSN': 'Motor_neuron',
    'I2': 'Pharyngeal_neuron',
    'Sperm': 'Germline',
    'VD_DD': 'Motor_neuron',
    'RIC': 'Interneuron',
    'AQR': 'Sensory_neuron',
    'VC': 'Motor_neuron',
    'Glia_3': 'Glia_unassigned',
    'RIV_stressed': 'Motor_neuron',
    'DB01': 'Motor_neuron',
    'VA': 'Motor_neuron',
    'Intestine': 'Intestine',
    'VB': 'Motor_neuron',
    'SAB': 'Motor_neuron',
    'OLL': 'Sensory_neuron',
    'URY': 'Sensory_neuron',
    'BAG': 'Sensory_neuron',
    'ALM': 'Sensory_neuron',
    'IL2_DV': 'Sensory_neuron',
    'AIA': 'Interneuron',
    'Excretory_gland_cell': 'Excretory_system',
    'M4': 'Pharyngeal_neuron',
    'RME_DV': 'Motor_neuron',
    'DB': 'Motor_neuron',
    'URA': 'Motor_neuron',
    'Vulval_muscle': 'Sex_muscle',
    'Distal_tip_cell': 'Somatic_gonad',
    'Anal_muscle': 'Enteric_muscle',
    'PHC': 'Sensory_neuron',
    'RME_LR': 'Motor_neuron',
    'PHsh': 'Glia_sheath',
    'I5': 'Pharyngeal_neuron',
    'RIB': 'Interneuron',
    'RIM': 'Motor_neuron',
    'ASI': 'Sensory_neuron',
    'AIM': 'Interneuron',
    'BDU': 'Interneuron',
    'DVB': 'Motor_neuron',
    'AIB': 'Interneuron',
    'I1': 'Pharyngeal_neuron',
    'Spermathecal-uterine_junction_or_uterine_toroid': 'Somatic_gonad',
    'RIS': 'Interneuron',
    'RIP': 'Interneuron',
    'DVC': 'Interneuron',
    'RMD_LR': 'Motor_neuron',
    'I6': 'Pharyngeal_neuron',
    'AVJ': 'Interneuron',
    'AMso': 'Glia_socket',
    'AUA': 'Interneuron',
    'Unknown_non-neuronal_3': 'Unknown',
    'RMG': 'Interneuron',
    'PLM': 'Sensory_neuron',
    'Body_wall_muscle_anterior': 'Body_wall_muscle',
    'Marginal_cell': 'Arcade_marginal',
    'hmc': 'Head_mesodermal_cell',
    'Pharyngeal_gland_cell': 'Pharyngeal_gland',
    'PDE': 'Sensory_neuron',
    'AWC_OFF': 'Sensory_neuron',
    'AVF': 'Interneuron',
    'AWB': 'Sensory_neuron',
    'AFD': 'Sensory_neuron',
    'Excretory_cell': 'Excretory_system',
    'Vulval_cells': 'Vulva',
    'Glia_5': 'Glia_unassigned',
    'FLP': 'Sensory_neuron',
    'SMD': 'Motor_neuron',
    'CAN': 'Neuron_other',
    'ADA': 'Interneuron',
    'Rectal_gland': 'Rectal_gland',
    'Glia_4': 'Glia_unassigned',
    'Unknown_non_neuronal_2': 'Unknown',
    'LUA': 'Interneuron',
    'ASEL': 'Sensory_neuron',
    'AMsh': 'Glia_sheath',
    'RIG': 'Interneuron',
    'PHso': 'Glia_socket',
    'Glia_2': 'Glia_unassigned',
    'OLQ': 'Sensory_neuron',
    'IL1': 'Sensory_neuron',
    'M3': 'Pharyngeal_neuron',
    'ALN': 'Interneuron',
    'AS': 'Motor_neuron',
    'DA9': 'Motor_neuron',
    'DVA': 'Interneuron',
    'PDA': 'Motor_neuron',
    'PDB': 'Motor_neuron',
    'PVD': 'Sensory_neuron',
    'PVM': 'Sensory_neuron',
    'PVN': 'Interneuron',
    'SAA': 'Interneuron',
    'VA12': 'Motor_neuron',
    'VC_4_5': 'Motor_neuron',
    'XXX': 'Atypical_XXX',
}

FOUNDER = {
    'Epidermis': 'AB',
    'ASG': 'AB',
    'Pharyngeal_muscle': 'AB',
    'PHB': 'AB',
    'PVT': 'AB',
    'VB02': 'AB',
    'Body_wall_muscle': 'MS',
    'ASK': 'AB',
    'ADL': 'AB',
    'IL2_LR': 'AB',
    'PHA': 'AB',
    'AVD': 'AB',
    'AVE': 'AB',
    'AWA': 'AB',
    'I4': 'MS',
    'ADE': 'AB',
    'PVW': 'AB',
    'SMB': 'AB',
    'ASH': 'AB',
    'SDQ': 'AB',
    'AVL': 'AB',
    'NSM': 'AB',
    'RMF': 'AB',
    'RMD_DV': 'AB',
    'Unannotated': 'NA',
    'CEP': 'AB',
    'SIA': 'AB',
    'ALA': 'AB',
    'Coelomocyte': 'MS',
    'AIZ': 'AB',
    'RMH': 'AB',
    'PLN': 'AB',
    'PVP': 'AB',
    'RIA': 'AB',
    'Germline': 'P4',
    'SMD_stressed': 'AB',
    'SIB': 'AB',
    'M5': 'MS',
    'RIR': 'AB',
    'URX': 'AB',
    'Uterine_cell': 'MS',
    'RIV': 'AB',
    'Seam_cell': 'AB',
    'AIN': 'AB',
    'PQR': 'AB',
    'AVH': 'AB',
    'AVK': 'AB',
    'VB01': 'AB',
    'RID': 'AB',
    'I3': 'MS',
    'Gonadal_sheath_cell': 'MS',
    'Glia_1': 'AB',
    'ASJ': 'AB',
    'AWC_ON': 'AB',
    'AVG': 'AB',
    'AVA': 'AB',
    'ASER': 'AB',
    'DA': 'AB',
    'URB': 'AB',
    'AVB': 'AB',
    'AVM': 'AB',
    'PVQ': 'AB',
    'CEPsh': 'AB',
    'M2': 'AB',
    'M1': 'MS',
    'Arcade_cell': 'AB',
    'RIF': 'AB',
    'MI': 'AB',
    'Spermatheca': 'MS',
    'PVR': 'C',
    'AIY': 'AB',
    'ADF': 'AB',
    'PVC': 'AB',
    'RIH': 'AB',
    'MC': 'AB',
    'Unknown_non_neuronal': 'NA',
    'HSN': 'AB',
    'I2': 'AB',
    'Sperm': 'P4',
    'VD_DD': 'AB',
    'RIC': 'AB',
    'AQR': 'AB',
    'VC': 'AB',
    'Glia_3': 'AB',
    'RIV_stressed': 'AB',
    'DB01': 'AB',
    'VA': 'AB',
    'Intestine': 'E',
    'VB': 'AB',
    'SAB': 'AB',
    'OLL': 'AB',
    'URY': 'AB',
    'BAG': 'AB',
    'ALM': 'AB',
    'IL2_DV': 'AB',
    'AIA': 'AB',
    'Excretory_gland_cell': 'AB',
    'M4': 'MS',
    'RME_DV': 'AB',
    'DB': 'AB',
    'URA': 'AB',
    'Vulval_muscle': 'MS',
    'Distal_tip_cell': 'MS',
    'Anal_muscle': 'AB',
    'PHC': 'AB',
    'RME_LR': 'AB',
    'PHsh': 'AB',
    'I5': 'AB',
    'RIB': 'AB',
    'RIM': 'AB',
    'ASI': 'AB',
    'AIM': 'AB',
    'BDU': 'AB',
    'DVB': 'AB',
    'AIB': 'AB',
    'I1': 'AB',
    'Spermathecal-uterine_junction_or_uterine_toroid': 'MS',
    'RIS': 'AB',
    'RIP': 'AB',
    'DVC': 'C',
    'RMD_LR': 'AB',
    'I6': 'MS',
    'AVJ': 'AB',
    'AMso': 'AB',
    'AUA': 'AB',
    'Unknown_non-neuronal_3': 'NA',
    'RMG': 'AB',
    'PLM': 'AB',
    'Body_wall_muscle_anterior': 'MS',
    'Marginal_cell': 'AB',
    'hmc': 'MS',
    'Pharyngeal_gland_cell': 'MS',
    'PDE': 'AB',
    'AWC_OFF': 'AB',
    'AVF': 'AB',
    'AWB': 'AB',
    'AFD': 'AB',
    'Excretory_cell': 'AB',
    'Vulval_cells': 'AB',
    'Glia_5': 'AB',
    'FLP': 'AB',
    'SMD': 'AB',
    'CAN': 'AB',
    'ADA': 'AB',
    'Rectal_gland': 'AB',
    'Glia_4': 'AB',
    'Unknown_non_neuronal_2': 'NA',
    'LUA': 'AB',
    'ASEL': 'AB',
    'AMsh': 'AB',
    'RIG': 'AB',
    'PHso': 'AB',
    'Glia_2': 'AB',
    'OLQ': 'AB',
    'IL1': 'AB',
    'M3': 'AB',
    'ALN': 'AB',
    'AS': 'AB',
    'DA9': 'AB',
    'DVA': 'AB',
    'PDA': 'AB',
    'PDB': 'AB',
    'PVD': 'AB',
    'PVM': 'AB',
    'PVN': 'AB',
    'SAA': 'AB',
    'VA12': 'AB',
    'VC_4_5': 'AB',
    'XXX': 'AB',
}

LINEAGE_MIXED = {
    'Epidermis': True,
    'ASG': False,
    'Pharyngeal_muscle': True,
    'PHB': False,
    'PVT': False,
    'VB02': False,
    'Body_wall_muscle': True,
    'ASK': False,
    'ADL': False,
    'IL2_LR': False,
    'PHA': False,
    'AVD': False,
    'AVE': False,
    'AWA': False,
    'I4': False,
    'ADE': False,
    'PVW': False,
    'SMB': False,
    'ASH': False,
    'SDQ': False,
    'AVL': False,
    'NSM': False,
    'RMF': False,
    'RMD_DV': False,
    'Unannotated': False,
    'CEP': False,
    'SIA': False,
    'ALA': False,
    'Coelomocyte': False,
    'AIZ': False,
    'RMH': False,
    'PLN': False,
    'PVP': False,
    'RIA': False,
    'Germline': False,
    'SMD_stressed': False,
    'SIB': False,
    'M5': False,
    'RIR': False,
    'URX': False,
    'Uterine_cell': False,
    'RIV': False,
    'Seam_cell': False,
    'AIN': False,
    'PQR': False,
    'AVH': False,
    'AVK': False,
    'VB01': False,
    'RID': False,
    'I3': False,
    'Gonadal_sheath_cell': False,
    'Glia_1': False,
    'ASJ': False,
    'AWC_ON': False,
    'AVG': False,
    'AVA': False,
    'ASER': False,
    'DA': False,
    'URB': False,
    'AVB': False,
    'AVM': False,
    'PVQ': False,
    'CEPsh': False,
    'M2': False,
    'M1': False,
    'Arcade_cell': False,
    'RIF': False,
    'MI': False,
    'Spermatheca': False,
    'PVR': False,
    'AIY': False,
    'ADF': False,
    'PVC': False,
    'RIH': False,
    'MC': False,
    'Unknown_non_neuronal': False,
    'HSN': False,
    'I2': False,
    'Sperm': False,
    'VD_DD': False,
    'RIC': False,
    'AQR': False,
    'VC': False,
    'Glia_3': False,
    'RIV_stressed': False,
    'DB01': False,
    'VA': False,
    'Intestine': False,
    'VB': False,
    'SAB': False,
    'OLL': False,
    'URY': False,
    'BAG': False,
    'ALM': False,
    'IL2_DV': False,
    'AIA': False,
    'Excretory_gland_cell': False,
    'M4': False,
    'RME_DV': False,
    'DB': False,
    'URA': False,
    'Vulval_muscle': False,
    'Distal_tip_cell': False,
    'Anal_muscle': True,
    'PHC': False,
    'RME_LR': False,
    'PHsh': False,
    'I5': False,
    'RIB': False,
    'RIM': False,
    'ASI': False,
    'AIM': False,
    'BDU': False,
    'DVB': False,
    'AIB': False,
    'I1': False,
    'Spermathecal-uterine_junction_or_uterine_toroid': False,
    'RIS': False,
    'RIP': False,
    'DVC': False,
    'RMD_LR': False,
    'I6': False,
    'AVJ': False,
    'AMso': False,
    'AUA': False,
    'Unknown_non-neuronal_3': False,
    'RMG': False,
    'PLM': False,
    'Body_wall_muscle_anterior': True,
    'Marginal_cell': True,
    'hmc': False,
    'Pharyngeal_gland_cell': False,
    'PDE': False,
    'AWC_OFF': False,
    'AVF': False,
    'AWB': False,
    'AFD': False,
    'Excretory_cell': False,
    'Vulval_cells': False,
    'Glia_5': False,
    'FLP': False,
    'SMD': False,
    'CAN': False,
    'ADA': False,
    'Rectal_gland': False,
    'Glia_4': False,
    'Unknown_non_neuronal_2': False,
    'LUA': False,
    'ASEL': False,
    'AMsh': False,
    'RIG': False,
    'PHso': False,
    'Glia_2': False,
    'OLQ': False,
    'IL1': False,
    'M3': False,
    'ALN': False,
    'AS': False,
    'DA9': False,
    'DVA': False,
    'PDA': False,
    'PDB': False,
    'PVD': False,
    'PVM': False,
    'PVN': False,
    'SAA': False,
    'VA12': False,
    'VC_4_5': False,
    'XXX': False,
}

FOUNDER_COMPOSITION = {
    'Epidermis': 'AB ~133 / C 13 (hyp7 + hyp11)',
    'ASG': 'AB',
    'Pharyngeal_muscle': 'AB 19 / MS 17',
    'PHB': 'AB',
    'PVT': 'AB',
    'VB02': 'AB',
    'Body_wall_muscle': 'MS 42 (28 embryonic + 14 postembryonic via M) / C 32 / D 20 / AB 1',
    'ASK': 'AB',
    'ADL': 'AB',
    'IL2_LR': 'AB',
    'PHA': 'AB',
    'AVD': 'AB',
    'AVE': 'AB',
    'AWA': 'AB',
    'I4': 'MS',
    'ADE': 'AB',
    'PVW': 'AB',
    'SMB': 'AB',
    'ASH': 'AB',
    'SDQ': 'AB',
    'AVL': 'AB',
    'NSM': 'AB',
    'RMF': 'AB',
    'RMD_DV': 'AB',
    'Unannotated': '',
    'CEP': 'AB',
    'SIA': 'AB',
    'ALA': 'AB',
    'Coelomocyte': 'MS 6/6 (ccAL/AR/PL/PR + 2 postembryonic from M)',
    'AIZ': 'AB',
    'RMH': 'AB',
    'PLN': 'AB',
    'PVP': 'AB',
    'RIA': 'AB',
    'Germline': 'P4 (Z2 = P4p, Z3 = P4a)',
    'SMD_stressed': 'AB',
    'SIB': 'AB',
    'M5': 'MS',
    'RIR': 'AB',
    'URX': 'AB',
    'Uterine_cell': 'MS (Z1/Z4 clone)',
    'RIV': 'AB',
    'Seam_cell': 'AB 20/20 (H0-H2, V1-V6, T)',
    'AIN': 'AB',
    'PQR': 'AB',
    'AVH': 'AB',
    'AVK': 'AB',
    'VB01': 'AB',
    'RID': 'AB',
    'I3': 'MS',
    'Gonadal_sheath_cell': 'MS (Z1/Z4 clone)',
    'Glia_1': 'AB',
    'ASJ': 'AB',
    'AWC_ON': 'AB',
    'AVG': 'AB',
    'AVA': 'AB',
    'ASER': 'AB',
    'DA': 'AB',
    'URB': 'AB',
    'AVB': 'AB',
    'AVM': 'AB',
    'PVQ': 'AB',
    'CEPsh': 'AB',
    'M2': 'AB',
    'M1': 'MS',
    'Arcade_cell': 'AB 9/9',
    'RIF': 'AB',
    'MI': 'AB',
    'Spermatheca': 'MS (Z1/Z4 clone)',
    'PVR': 'C',
    'AIY': 'AB',
    'ADF': 'AB',
    'PVC': 'AB',
    'RIH': 'AB',
    'MC': 'AB',
    'Unknown_non_neuronal': '',
    'HSN': 'AB',
    'I2': 'AB',
    'Sperm': 'P4 (Z2/Z3 clone)',
    'VD_DD': 'AB',
    'RIC': 'AB',
    'AQR': 'AB',
    'VC': 'AB',
    'Glia_3': 'AB',
    'RIV_stressed': 'AB',
    'DB01': 'AB',
    'VA': 'AB',
    'Intestine': 'E 20/20',
    'VB': 'AB',
    'SAB': 'AB',
    'OLL': 'AB',
    'URY': 'AB',
    'BAG': 'AB',
    'ALM': 'AB',
    'IL2_DV': 'AB',
    'AIA': 'AB',
    'Excretory_gland_cell': 'AB 2/2 (exc_gl_L, exc_gl_R)',
    'M4': 'MS',
    'RME_DV': 'AB',
    'DB': 'AB',
    'URA': 'AB',
    'Vulval_muscle': 'MS 8/8 (vm1, vm2 via M -> SM)',
    'Distal_tip_cell': 'MS (Z1/Z4 clone)',
    'Anal_muscle': 'AB 3 (mu_anal, mu_sph, mu_int_L) / MS 1 (mu_int_R)',
    'PHC': 'AB',
    'RME_LR': 'AB',
    'PHsh': 'AB',
    'I5': 'AB',
    'RIB': 'AB',
    'RIM': 'AB',
    'ASI': 'AB',
    'AIM': 'AB',
    'BDU': 'AB',
    'DVB': 'AB',
    'AIB': 'AB',
    'I1': 'AB',
    'Spermathecal-uterine_junction_or_uterine_toroid': 'MS (Z1/Z4 clone)',
    'RIS': 'AB',
    'RIP': 'AB',
    'DVC': 'C',
    'RMD_LR': 'AB',
    'I6': 'MS',
    'AVJ': 'AB',
    'AMso': 'AB',
    'AUA': 'AB',
    'Unknown_non-neuronal_3': '',
    'RMG': 'AB',
    'PLM': 'AB',
    'Body_wall_muscle_anterior': 'MS-dominant (head/neck muscles)',
    'Marginal_cell': 'AB 7 (mc1, mc2, mc3V) / MS 2 (mc3DL, mc3DR)',
    'hmc': 'MS 1/1',
    'Pharyngeal_gland_cell': 'MS 5/5 (g1AL, g1AR, g1P, g2L, g2R)',
    'PDE': 'AB',
    'AWC_OFF': 'AB',
    'AVF': 'AB',
    'AWB': 'AB',
    'AFD': 'AB',
    'Excretory_cell': 'AB (exc_cell = ABplpappaap)',
    'Vulval_cells': 'AB 22/22',
    'Glia_5': 'AB',
    'FLP': 'AB',
    'SMD': 'AB',
    'CAN': 'AB',
    'ADA': 'AB',
    'Rectal_gland': 'AB 3/3 (rect_D, rect_VL, rect_VR)',
    'Glia_4': 'AB',
    'Unknown_non_neuronal_2': '',
    'LUA': 'AB',
    'ASEL': 'AB',
    'AMsh': 'AB',
    'RIG': 'AB',
    'PHso': 'AB',
    'Glia_2': 'AB',
    'OLQ': 'AB',
    'IL1': 'AB',
    'M3': 'AB',
    'ALN': 'AB',
    'AS': 'AB',
    'DA9': 'AB',
    'DVA': 'AB',
    'PDA': 'AB',
    'PDB': 'AB',
    'PVD': 'AB',
    'PVM': 'AB',
    'PVN': 'AB',
    'SAA': 'AB',
    'VA12': 'AB',
    'VC_4_5': 'AB',
    'XXX': 'AB 2/2 (XXXL = AB plaaapaa, XXXR = AB arpappaa)',
}

CONFIDENCE = {
    'Epidermis': 'high',
    'ASG': 'high',
    'Pharyngeal_muscle': 'high',
    'PHB': 'high',
    'PVT': 'high',
    'VB02': 'high',
    'Body_wall_muscle': 'high',
    'ASK': 'high',
    'ADL': 'high',
    'IL2_LR': 'high',
    'PHA': 'high',
    'AVD': 'high',
    'AVE': 'high',
    'AWA': 'high',
    'I4': 'high',
    'ADE': 'high',
    'PVW': 'high',
    'SMB': 'high',
    'ASH': 'high',
    'SDQ': 'high',
    'AVL': 'high',
    'NSM': 'high',
    'RMF': 'high',
    'RMD_DV': 'high',
    'Unannotated': 'none',
    'CEP': 'high',
    'SIA': 'high',
    'ALA': 'high',
    'Coelomocyte': 'high',
    'AIZ': 'high',
    'RMH': 'high',
    'PLN': 'high',
    'PVP': 'high',
    'RIA': 'high',
    'Germline': 'high',
    'SMD_stressed': 'high',
    'SIB': 'high',
    'M5': 'high',
    'RIR': 'high',
    'URX': 'high',
    'Uterine_cell': 'high',
    'RIV': 'high',
    'Seam_cell': 'high',
    'AIN': 'high',
    'PQR': 'high',
    'AVH': 'high',
    'AVK': 'high',
    'VB01': 'high',
    'RID': 'high',
    'I3': 'high',
    'Gonadal_sheath_cell': 'high',
    'Glia_1': 'medium',
    'ASJ': 'high',
    'AWC_ON': 'high',
    'AVG': 'high',
    'AVA': 'high',
    'ASER': 'high',
    'DA': 'high',
    'URB': 'high',
    'AVB': 'high',
    'AVM': 'high',
    'PVQ': 'high',
    'CEPsh': 'high',
    'M2': 'high',
    'M1': 'high',
    'Arcade_cell': 'high',
    'RIF': 'high',
    'MI': 'high',
    'Spermatheca': 'high',
    'PVR': 'high',
    'AIY': 'high',
    'ADF': 'high',
    'PVC': 'high',
    'RIH': 'high',
    'MC': 'high',
    'Unknown_non_neuronal': 'none',
    'HSN': 'high',
    'I2': 'high',
    'Sperm': 'high',
    'VD_DD': 'high',
    'RIC': 'high',
    'AQR': 'high',
    'VC': 'high',
    'Glia_3': 'medium',
    'RIV_stressed': 'high',
    'DB01': 'high',
    'VA': 'high',
    'Intestine': 'high',
    'VB': 'high',
    'SAB': 'high',
    'OLL': 'high',
    'URY': 'high',
    'BAG': 'high',
    'ALM': 'high',
    'IL2_DV': 'high',
    'AIA': 'high',
    'Excretory_gland_cell': 'high',
    'M4': 'high',
    'RME_DV': 'high',
    'DB': 'high',
    'URA': 'high',
    'Vulval_muscle': 'high',
    'Distal_tip_cell': 'high',
    'Anal_muscle': 'high',
    'PHC': 'high',
    'RME_LR': 'high',
    'PHsh': 'high',
    'I5': 'high',
    'RIB': 'high',
    'RIM': 'high',
    'ASI': 'high',
    'AIM': 'high',
    'BDU': 'high',
    'DVB': 'high',
    'AIB': 'high',
    'I1': 'high',
    'Spermathecal-uterine_junction_or_uterine_toroid': 'high',
    'RIS': 'high',
    'RIP': 'high',
    'DVC': 'high',
    'RMD_LR': 'high',
    'I6': 'high',
    'AVJ': 'high',
    'AMso': 'high',
    'AUA': 'high',
    'Unknown_non-neuronal_3': 'none',
    'RMG': 'high',
    'PLM': 'high',
    'Body_wall_muscle_anterior': 'medium',
    'Marginal_cell': 'high',
    'hmc': 'high',
    'Pharyngeal_gland_cell': 'high',
    'PDE': 'high',
    'AWC_OFF': 'high',
    'AVF': 'high',
    'AWB': 'high',
    'AFD': 'high',
    'Excretory_cell': 'high',
    'Vulval_cells': 'high',
    'Glia_5': 'medium',
    'FLP': 'high',
    'SMD': 'high',
    'CAN': 'high',
    'ADA': 'high',
    'Rectal_gland': 'high',
    'Glia_4': 'medium',
    'Unknown_non_neuronal_2': 'none',
    'LUA': 'high',
    'ASEL': 'high',
    'AMsh': 'high',
    'RIG': 'high',
    'PHso': 'high',
    'Glia_2': 'medium',
    'OLQ': 'high',
    'IL1': 'high',
    'M3': 'high',
    'ALN': 'high',
    'AS': 'high',
    'DA9': 'high',
    'DVA': 'high',
    'PDA': 'high',
    'PDB': 'high',
    'PVD': 'high',
    'PVM': 'high',
    'PVN': 'high',
    'SAA': 'high',
    'VA12': 'high',
    'VC_4_5': 'high',
    'XXX': 'high',
}

NOTES = {
    'Epidermis': 'hyp1-hyp12 syncytia; AB-dominant, with a definite C-lineage contribution to hyp7 and all of hyp11.',
    'ASG': '',
    'Pharyngeal_muscle': 'Near-even AB/MS split. pm1, pm2 and mc-adjacent anterior muscles are ABa; pm4-pm8 are largely MS; pm3/pm4/pm5 contain identical cells of BOTH origins that later fuse into syncytia (WormAtlas). Do NOT treat this cluster as one lineage.',
    'PHB': '',
    'PVT': '',
    'VB02': '',
    'Body_wall_muscle': 'Of the 81 muscles at hatching: 20 D, 16 Ca, 16 Cp, 9 MSpp, 6 MSpa, 9 MSap, 4 MSaa, 1 AB (ABprpppppa). 14 more arise postembryonically from M (MSapaapp). The single richest multi-founder cluster in the dataset.',
    'ASK': '',
    'ADL': '',
    'IL2_LR': '',
    'PHA': '',
    'AVD': '',
    'AVE': '',
    'AWA': '',
    'I4': 'One of only 6 MS-derived neurons.',
    'ADE': '',
    'PVW': '',
    'SMB': '',
    'ASH': '',
    'SDQ': 'AB, from QL/QR.',
    'AVL': 'AB; GABAergic enteric motor neuron (classified interneuron by WormAtlas).',
    'NSM': 'AB-derived despite being a pharyngeal neuron (NSML/R = AB alpaapaav / AB arapapaav).',
    'RMF': '',
    'RMD_DV': '',
    'Unannotated': 'Not assignable.',
    'CEP': '',
    'SIA': '',
    'ALA': '',
    'Coelomocyte': '',
    'AIZ': '',
    'RMH': '',
    'PLN': '',
    'PVP': '',
    'RIA': '',
    'Germline': 'The only P4/germline-derived cluster besides Sperm. Strictly clonal.',
    'SMD_stressed': 'Stress-response subcluster of SMD; same identity/lineage as SMD.',
    'SIB': '',
    'M5': 'One of only 6 MS-derived neurons.',
    'RIR': '',
    'URX': '',
    'Uterine_cell': 'Whole somatic gonad is the Z1 + Z4 clone. Z1 = MS pppaap, Z4 = MS appaap - i.e. one somatic gonad precursor from MSa and one from MSp, so the somatic gonad is bi-clonal below MS.',
    'RIV': '',
    'Seam_cell': 'WormAtlas seam page: "All derive from the AB lineage." Split ABa 12 / ABp 8.',
    'AIN': '',
    'PQR': 'AB, from the QL neuroblast (AB plapapaaa).',
    'AVH': '',
    'AVK': '',
    'VB01': '',
    'RID': '',
    'I3': 'One of only 6 MS-derived neurons.',
    'Gonadal_sheath_cell': '',
    'Glia_1': 'Unnamed CeNGEN glial cluster. All named neuroectodermal glia are AB; the 6 GLR glia are MS, so if any unnamed glial cluster is GLR its founder is MS. Flagged medium confidence.',
    'ASJ': '',
    'AWC_ON': '',
    'AVG': '',
    'AVA': '',
    'ASER': '',
    'DA': '',
    'URB': '',
    'AVB': '',
    'AVM': 'AB, from QR.',
    'PVQ': '',
    'CEPsh': 'Neuroectodermal glia, AB-derived.',
    'M2': '',
    'M1': 'One of only 6 MS-derived neurons.',
    'Arcade_cell': 'Anterior + posterior arcade cells, all ABa (ABal/ABar).',
    'RIF': '',
    'MI': '',
    'Spermatheca': '',
    'PVR': 'One of only TWO C-derived neurons (with DVC). Useful positive control for C-lineage tracing.',
    'AIY': '',
    'ADF': '',
    'PVC': '',
    'RIH': '',
    'MC': '',
    'Unknown_non_neuronal': 'Not assignable.',
    'HSN': 'AB; hermaphrodite-specific, born in the tail and migrates.',
    'I2': '',
    'Sperm': '',
    'VD_DD': '',
    'RIC': '',
    'AQR': 'AB, from the QR neuroblast (AB prapapaaa).',
    'VC': '',
    'Glia_3': 'Unnamed CeNGEN glial cluster. All named neuroectodermal glia are AB; the 6 GLR glia are MS, so if any unnamed glial cluster is GLR its founder is MS. Flagged medium confidence.',
    'RIV_stressed': 'Stress-response subcluster of RIV; same identity/lineage as RIV.',
    'DB01': '',
    'VA': '',
    'Intestine': 'The only strictly clonal tissue: the entire intestine is the E clone (10 Ea + 10 Ep).',
    'VB': '',
    'SAB': '',
    'OLL': '',
    'URY': '',
    'BAG': '',
    'ALM': '',
    'IL2_DV': '',
    'AIA': '',
    'Excretory_gland_cell': '',
    'M4': 'One of only 6 MS-derived neurons.',
    'RME_DV': '',
    'DB': '',
    'URA': '',
    'Vulval_muscle': 'M mesoblast = MSapaapp; sex myoblasts make vm1/vm2 (and um1/um2).',
    'Distal_tip_cell': '',
    'Anal_muscle': 'mu_anal, mu_sph and mu_int_L come from the ABp(l/r)pppppa group (the same group that makes the one AB-derived body wall muscle); mu_int_R is MS (MS ppaapp). Left/right asymmetric in founder origin.',
    'PHC': '',
    'RME_LR': '',
    'PHsh': 'Neuroectodermal glia, AB-derived.',
    'I5': '',
    'RIB': '',
    'RIM': '',
    'ASI': '',
    'AIM': '',
    'BDU': '',
    'DVB': 'AB (from the K blast cell, K = AB plpapppaa); enteric motor neuron.',
    'AIB': '',
    'I1': '',
    'Spermathecal-uterine_junction_or_uterine_toroid': '',
    'RIS': '',
    'RIP': 'AB; the only direct pharynx-to-nerve-ring connection, but itself extrapharyngeal.',
    'DVC': 'One of only TWO C-derived neurons (with PVR). Useful positive control for C-lineage tracing.',
    'RMD_LR': '',
    'I6': 'One of only 6 MS-derived neurons.',
    'AVJ': '',
    'AMso': 'Neuroectodermal glia, AB-derived.',
    'AUA': '',
    'Unknown_non-neuronal_3': 'Not assignable.',
    'RMG': '',
    'PLM': '',
    'Body_wall_muscle_anterior': 'Head (4 anteriormost per quadrant) + neck (next 4) muscles. Founder identity cannot be read off the CeNGEN label; assigned MS because MS-derived muscles occupy anterior positions, but the position-to-lineage correspondence was NOT verified cell-by-cell here. Treat as soft.',
    'Marginal_cell': 'mc1 and mc2 rings are ABa; the mc3 ring is split - mc3V is AB, mc3DL/DR are MS.',
    'hmc': 'Head mesodermal cell; sister of a somatic gonad precursor in the MS lineage.',
    'Pharyngeal_gland_cell': 'All five pharyngeal gland cells are MS (e.g. g1P = MS aaaaapap).',
    'PDE': 'AB, from the V5 seam blast cell postembryonically.',
    'AWC_OFF': '',
    'AVF': '',
    'AWB': '',
    'AFD': '',
    'Excretory_cell': 'Excretory canal cell; sister of RMEV.',
    'Vulval_cells': 'vulA-vulF from P5.p/P6.p/P7.p; P cells are AB-derived (P1/2L = ABplapaapp etc.).',
    'Glia_5': 'Unnamed CeNGEN glial cluster. All named neuroectodermal glia are AB; the 6 GLR glia are MS, so if any unnamed glial cluster is GLR its founder is MS. Flagged medium confidence.',
    'FLP': '',
    'SMD': '',
    'CAN': 'AB; migratory, no synapses.',
    'ADA': '',
    'Rectal_gland': '',
    'Glia_4': 'Unnamed CeNGEN glial cluster. All named neuroectodermal glia are AB; the 6 GLR glia are MS, so if any unnamed glial cluster is GLR its founder is MS. Flagged medium confidence.',
    'Unknown_non_neuronal_2': 'Not assignable.',
    'LUA': '',
    'ASEL': '',
    'AMsh': 'Neuroectodermal glia, AB-derived.',
    'RIG': '',
    'PHso': 'Neuroectodermal glia, AB-derived.',
    'Glia_2': 'Unnamed CeNGEN glial cluster. All named neuroectodermal glia are AB; the 6 GLR glia are MS, so if any unnamed glial cluster is GLR its founder is MS. Flagged medium confidence.',
    'OLQ': '',
    'IL1': '',
    'M3': '',
    'ALN': 'AB; sister-lineage partner of ALM (AB plapappppap / AB prapappppap).',
    'AS': 'AB, from the Pn.apa ventral cord blast lineage (AS1-AS11).',
    'DA9': 'AB; individual DA-class member, separated by CeNGEN.',
    'DVA': 'AB (AB prppppapp), cell body in the dorsorectal ganglion - NOT to be confused with DVC, which is one of the two C-derived neurons.',
    'PDA': 'AB; the Y cell (AB prpppaaaa) transdifferentiates into PDA in the hermaphrodite.',
    'PDB': 'AB (P12.apa).',
    'PVD': 'AB, from the V5 seam blast cell (V5L/R.paapa) - same postembryonic lineage as PDE.',
    'PVM': 'AB, from the QL neuroblast (QL.paa).',
    'PVN': 'AB, from the T seam blast cell (TL/TR.appp). WormAtlas calls it interneuron/motor neuron; placed in Interneuron here.',
    'SAA': 'AB (SAADL/R, SAAVL/R).',
    'VA12': 'AB (P12.aaaa); individual VA-class member, separated by CeNGEN.',
    'VC_4_5': 'AB (P6.aap, P7.aap); the two vulva-proximal VC neurons, separated by CeNGEN.',
    'XXX': 'XXXL/R are born as anterior head hypodermal cells, then delaminate and act as neuroendocrine cells (the DAF-9 steroidogenic cells). Ectodermal/AB origin, not a neuron and not mesoderm; grouped under Epithelium to reflect its hypodermal birth.',
}


#: founders that are informative for lineage tracing (excludes unassignable)
FOUNDERS = ("AB", "MS", "E", "C", "D", "P4")

#: labels whose founder assignment is a single clean clone (safe as ground truth)
CLEAN_LINEAGE_LABELS = tuple(k for k, v in LINEAGE_MIXED.items()
                             if not v and FOUNDER[k] in FOUNDERS)

#: labels that pool more than one founder -- see FOUNDER_COMPOSITION before using
MIXED_LINEAGE_LABELS = tuple(k for k, v in LINEAGE_MIXED.items() if v)

#: what an unrecognised label gets, per output column
UNMAPPED_FILL = {
    "tissue_coarse": "Unknown",
    "tissue_medium": "Unknown",
    "founder": "NA",
    "founder_composition": "",
    "confidence": "none",
    "lineage_mixed": False,
}

_TABLES = {
    "tissue_coarse": TISSUE_COARSE,
    "tissue_medium": TISSUE_MEDIUM,
    "founder": FOUNDER,
    "founder_composition": FOUNDER_COMPOSITION,
    "confidence": CONFIDENCE,
}


def check_labels(labels):
    """Return the sorted set of labels that have no entry in the map."""
    return sorted(set(map(str, labels)) - set(FOUNDER))


def annotate(adata, key="cell_type", prefix="", on_missing="ignore", verbose=True):
    """Add tissue / founder-lineage columns to ``adata.obs``.

    Adds ``tissue_coarse``, ``tissue_medium``, ``founder``, ``founder_composition``,
    ``confidence`` and ``lineage_mixed`` (optionally with ``prefix``).

    Parameters
    ----------
    adata : AnnData with CeNGEN labels in ``adata.obs[key]``.
    key : str
        obs column holding the cell-type label.
    prefix : str
        optional prefix for the new obs column names.
    on_missing : {"ignore", "raise", "silent"}
        What to do with labels absent from the map. ``"ignore"`` (default) fills them
        with ``UNMAPPED_FILL`` and warns; ``"silent"`` fills without warning;
        ``"raise"`` raises KeyError.
    verbose : bool
        Set False to suppress the warning under ``on_missing="ignore"``.
    """
    import warnings
    import pandas as pd

    if on_missing not in ("ignore", "raise", "silent"):
        raise ValueError('on_missing must be "ignore", "raise" or "silent"')

    lab = adata.obs[key].astype(str)
    missing = check_labels(lab.unique())
    if missing:
        if on_missing == "raise":
            raise KeyError(f"labels not in map: {missing}")
        if on_missing == "ignore" and verbose:
            n = int(lab.isin(missing).sum())
            warnings.warn(
                f"{len(missing)} label(s) not in the lineage map "
                f"({n} cells) left unannotated: {missing}",
                stacklevel=2,
            )

    for name, table in _TABLES.items():
        vals = lab.map(table).fillna(UNMAPPED_FILL[name])
        adata.obs[prefix + name] = pd.Categorical(vals)
    adata.obs[prefix + "lineage_mixed"] = (
        lab.map(LINEAGE_MIXED).fillna(UNMAPPED_FILL["lineage_mixed"]).astype(bool).values
    )
    return adata
