#!/bin/bash
mkdir -p coverage_tracks
sbatch -p short coverage_tracks.py CAACTTGCAGGAAGATGGTCACTCTATGCGACAAGGGATGGTCTA human mMDA
sbatch -p short coverage_tracks.py TACCACAGAGGATTGGTAGCACTCGTGTGATGAAGGCGACCTATA human mMDA
sbatch -p short coverage_tracks.py CAACTTGCAGGAAAGGTGACACTCTACAACCGAAGGAGATACCGA human mMDA
sbatch -p short coverage_tracks.py ACTAACCGAGGAAAGGTGACACTCCGAACTTGAAGGGATGGTCTA human mMDA
sbatch -p short coverage_tracks.py CAACTTGCAGGATGGTCACTACTCTCCAGTCTAAGGCGGTTGATA human mMDA
sbatch -p short coverage_tracks.py CAACCAACAGGAAGGCATTGACTCTCTGCTTGAAGGGGCATCAAA human mMDA
sbatch -p short coverage_tracks.py CAACTTGCAGGAAGGCTAACACTCGTGTGATGAAGGGACAGCATA mouse mMDA
sbatch -p short coverage_tracks.py ACTAACCGAGGAATGGTGTGACTCAGGTCGTAAAGGCGACCTATA mouse mMDA
sbatch -p short coverage_tracks.py AGGTCCAAAGGATGGTCACTACTCAGCATTGGAAGGGATGGTCTA mouse mMDA
sbatch -p short coverage_tracks.py GGTCTCATAGGATGGTCACTACTCAGAATGCCAAGGCGACCTATA mouse mMDA
sbatch -p short coverage_tracks.py CAACTTGCAGGATTGGTAGCACTCGGAACTGTAAGGGATGGTCTA mouse mMDA
sbatch -p short coverage_tracks.py GGTCTCATAGGAGATACCGAACTCTACAACCGAAGGCGACCTATA mouse mMDA
sbatch -p short coverage_tracks.py AGGTCCAAAGGAAGACCGATACTCACAGTAGCAAGGGTCGGTAAA human PTA	
sbatch -p short coverage_tracks.py GGTCTCATAGGAAGGCATTGACTCTGTTGGACAAGGTTGGATGCA human PTA	
sbatch -p short coverage_tracks.py TACCACAGAGGATGGTCACTACTCAGGTCGTAAAGGGTCGGTAAA human PTA	
sbatch -p short coverage_tracks.py ACTAACCGAGGAGATACCGAACTCTGCTATGGAAGGTTGATGGCA human PTA	
sbatch -p short coverage_tracks.py GTGAGACTAGGAATGGTGTGACTCGCTGGATAAAGGGTCGGTAAA human PTA	
sbatch -p short coverage_tracks.py CAACCAACAGGAAACTGCTCACTCTCTGGAACAAGGCATACCGTA human PTA	
sbatch -p short coverage_tracks.py AGGTCCAAAGGATGGTCACTACTCTATGCGACAAGGGTCGGTAAA mouse PTA	
sbatch -p short coverage_tracks.py TATCAGCCAGGAAGATGGTCACTCACAGTAGCAAGGGTTACGGTA mouse PTA	
sbatch -p short coverage_tracks.py CAACCAACAGGAGATACCGAACTCACAGTAGCAAGGACATCGTCA mouse PTA	
sbatch -p short coverage_tracks.py ACTAACCGAGGAAGGCATTGACTCTGCTATGGAAGGTTGGATGCA mouse PTA	
sbatch -p short coverage_tracks.py GGTCTCATAGGATGGTCACTACTCTCTGCTTGAAGGACATCGTCA mouse PTA	
sbatch -p short coverage_tracks.py TACCACAGAGGAAACGATGGACTCTATGCGACAAGGGTCGGTAAA mouse PTA	